# Generated by Django 4.2.1 on 2023-05-31 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_bc_id'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customers', to_field='bc_id'),
        ),
    ]
