# Generated by Django 4.2.1 on 2023-05-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_addresses_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='address_id',
            field=models.IntegerField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
