# Generated by Django 4.2.1 on 2023-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_addresses_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_id',
            field=models.IntegerField(unique=True),
        ),
    ]
