# Generated by Django 4.2.1 on 2023-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_addresses_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
