# Generated by Django 4.2.1 on 2023-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'cart_item', 'verbose_name_plural': 'cart_items'},
        ),
        migrations.AlterModelTable(
            name='cartitems',
            table='cart_items',
        ),
    ]
