# Generated by Django 4.2.1 on 2023-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('new_password', models.CharField(max_length=200)),
                ('bc_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'customers',
                'verbose_name_plural': 'customers',
                'db_table': 'customers',
            },
        ),
    ]
