# Generated by Django 4.2.1 on 2023-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='bc_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
