# Generated by Django 4.2.1 on 2023-06-05 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_products_price'),
        ('customers', '0002_alter_customers_bc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bc_order_id', models.IntegerField(default=0, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Pending'), (2, 'Shipped'), (3, 'Partially Shipped'), (4, 'Refunded'), (5, 'Cancelled'), (6, 'Declined'), (7, 'Awaiting Payment'), (8, 'Awaiting Pickup'), (9, 'Awaiting Shipment'), (10, 'Completed'), (11, 'Awaiting Fulfillment'), (12, 'Manual Verification Required'), (13, 'Disputed'), (14, 'Partially Refunded')])),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customers', to_field='bc_id')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders', to_field='bc_order_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', to_field='bc_pro_id')),
            ],
            options={
                'verbose_name': 'order_item',
                'verbose_name_plural': 'order_items',
                'db_table': 'order_items',
            },
        ),
    ]
