# Generated by Django 4.2.1 on 2023-06-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_addresses_address_id'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.DO_NOTHING, to='addresses.addresses', to_field='address_id'),
            preserve_default=False,
        ),
    ]
